---
# tasks file for base

- name: Includiung OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Check for unsupported target operating system
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: base_supported_os is not defined

- name: setup the rack user
  user: name={{ base_username }} comment="Rackspace Support" state=present shell=/bin/bash

- name: setup ssh keys for rack user
  authorized_key: user={{ base_username }} key="{{ item }}"
  with_items: rax_pub_keys
  when: rax_pub_keys is defined
  
- name: setup sudo for includedir
  template: src=sudoers.j2 dest=/etc/sudoers validate='visudo -cf %s' owner=root group=root mode=0440

- name: setup sudo for rack user
  template: src=80-rack-user.j2 dest=/etc/sudoers.d/80-rack-user validate='visudo -cf %s' owner=root group=root mode=0440

- name: ensure ntp is running
  service: name={{ base_ntp_service_name }} state=started

- name: configure fail2ban whitelist
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local owner=root group=root mode=0644
  notify: restart fail2ban

- name: ensure fail2ban is running
  service: name=fail2ban state=started

- name: configure motd
  copy: src=motd.tail dest={{ base_motd_location }} owner=root group=root mode=0644