---
# tasks file for base
- name: setup the rack user
  user: name=rack comment="Rackspace Support" state=present shell=/bin/bash

- name: setup ssh keys for rack user
  authorized_key: user=rack key="{{ item }}"
  with_items: rax_pub_keys

- name: python-apt hack until 1.6
  raw: apt-get update && apt-get install python-apt -y -q

- name: install necessary admin packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items: admin_packages

- name: ensure ntp is running
  service: name=ntp state=started

- name: configure motd
  copy: src=motd.tail dest=/etc/motd.tail owner=root group=root mode=0644

- name: replace missing update-motd.d script
  copy: src=99-footer dest=/etc/update-motd.d/99-footer owner=root group=root mode=0755
